# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MaptextAnnotator
                                 A QGIS plugin
 This plugin can be used to annotate text on maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-03
        copyright            : (C) 2026 by Daniel Seisenbacher
        email                : dasebdu@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MaptextAnnotator class from file MaptextAnnotator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MaptextAnnotator import MaptextAnnotator
    return MaptextAnnotator(iface)
