# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MaptextAnnotator
                                 A QGIS plugin
 This plugin can be used to annotate text on maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-06-03
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Daniel Seisenbacher
        email                : dasebdu@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsVectorLayer, QgsField, QgsProject, QgsRasterLayer, QgsGeometry, QgsCoordinateTransform
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .MaptextAnnotator_dockwidget import MaptextAnnotatorDockWidget
import os.path


class MaptextAnnotator:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'MaptextAnnotator_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&MapText Annotator')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'MaptextAnnotator')
        self.toolbar.setObjectName(u'MaptextAnnotator')

        #print "** INITIALIZING MaptextAnnotator"

        self.pluginIsActive = False
        self.dockwidget = None

        self.current_annotation_layer = None
        self.root = QgsProject.instance().layerTreeRoot()


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('MaptextAnnotator', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/MaptextAnnotator/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Annotate MapText'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING MaptextAnnotator"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD MaptextAnnotator"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&MapText Annotator'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING MaptextAnnotator"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = MaptextAnnotatorDockWidget()

                self.dockwidget.generateLayer.clicked.connect(self.createPolyLayer)
                self.dockwidget.annotationLayerCombo.layerChanged.connect(self.updateDatasetStats)  # react to changes

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.updateDatasetStats() # inital run for startup
            self.dockwidget.show()

    def createPolyLayer(self):
        count = 2
        base_name, annotation_layer_name = "Annotation Layer", "Annotation Layer"
        while True:
            exists = QgsProject.instance().mapLayersByName(annotation_layer_name)
            if exists:
                annotation_layer_name = base_name + f" {count}"
                count += 1
                continue
            break

        vl = QgsVectorLayer("Polygon", annotation_layer_name, "memory")
        pr = vl.dataProvider()

        pr.addAttributes([QgsField(name, type) for name, type in self.dockwidget.required_fields.items()])
        vl.updateFields()
        vl.loadNamedStyle(os.path.join(self.plugin_dir, "annotator_style.qml"))
        QgsProject.instance().addMapLayer(vl)


    def updateDatasetStats(self):
        """
        This function reacts to changes in the Annotation Polygon Layer Combobox
        """

        # disconnect from old layer
        if self.current_annotation_layer is not None:
            try:
                self.current_annotation_layer.featureAdded.disconnect(self.gatherLayerStats)
                self.current_annotation_layer.featureDeleted.disconnect(self.gatherLayerStats)
            except:
                pass
            self.current_annotation_layer = None

        current_layer = self.dockwidget.annotationLayerCombo.currentLayer()

        if not current_layer:
            self.dockwidget.labelCountLabel.setText("None Selected")
            self.dockwidget.phraseCountLabel.setText("None Selected")
            self.dockwidget.imageCountLabel.setText("None Selected")
            return

        self.current_annotation_layer = current_layer
        current_layer.featureAdded.connect(self.gatherLayerStats)
        current_layer.featureDeleted.connect(self.gatherLayerStats)


    def gatherLayerStats(self, fid):
        """
        This function reacts to changes in the currently selected Annotation Polygon Layer Combobox layer to update
        stats.
        """
        if not self.current_annotation_layer:
            return

        # link the image that is used to for label creation
        self.insert_image_reference(fid)

        # overall layer stats
        label_count = self.current_annotation_layer.featureCount()
        phrases = sum(1 for f in self.current_annotation_layer.getFeatures() if not f["Link to previous Word"])
        images = self.current_annotation_layer.uniqueValues(self.current_annotation_layer.fields().indexOf("Reference Image"))
        image_count = len(images)

        self.dockwidget.labelCountLabel.setText(str(label_count))
        self.dockwidget.phraseCountLabel.setText(str(phrases))
        self.dockwidget.imageCountLabel.setText(str(image_count))


    def insert_image_reference(self, fid):
        """
        Check what is the layer on top of which is being annotated
        """

        # first check which layers intersects with a given region
        feature = self.current_annotation_layer.getFeature(fid)
        geom = feature.geometry()

        # find all raster layers in the project
        raster_layers = [
            layer for layer in QgsProject.instance().mapLayers().values()
            if isinstance(layer, QgsRasterLayer)
        ]

        # check which rasters intersect with the feature geometry
        intersecting = []
        annotation_crs = self.current_annotation_layer.crs()
        for raster in raster_layers:
            # reproject feature geometry to raster CRS
            crs = raster.crs()
            if not crs.isValid():
                crs = QgsProject.instance().crs()

            transform = QgsCoordinateTransform(
                annotation_crs,
                crs,
                QgsProject.instance()
            )
            geom_transformed = QgsGeometry(geom)  # copy
            geom_transformed.transform(transform)

            raster_extent = QgsGeometry.fromRect(raster.extent())
            if geom_transformed.intersects(raster_extent):
                intersecting.append(raster)


        # Keep only visible intersecting rasters
        visible_intersecting = [
            layer for layer in intersecting
            if self.root.findLayer(layer.id()).isVisible()
        ]

        image_reference = "None found"
        if visible_intersecting:
            # Layer order from bottom -> top
            layer_order = QgsProject.instance().layerTreeRoot().layerOrder()
            print(layer_order)

            # Find the visible intersecting layer that is highest in the stack
            topmost_layer = min(
                visible_intersecting,
                key=lambda lyr: layer_order.index(lyr)
            )

            image_reference = topmost_layer.name()

        self.current_annotation_layer.startEditing()

        field_idx = self.current_annotation_layer.fields().indexOf("Reference Image")
        self.current_annotation_layer.changeAttributeValue(feature.id(), field_idx, image_reference)

        self.current_annotation_layer.commitChanges()




