# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MaptextAnnotatorDockWidget
                                 A QGIS plugin
 This plugin can be used to annotate text on maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-03
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Daniel Seisenbacher
        email                : dasebdu@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal, QVariant
from qgis.core import QgsMapLayerProxyModel, QgsProject, QgsVectorLayer
from .resources import *

FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'MaptextAnnotator_dockwidget_base.ui'))

def layer_has_required_fields(layer, required_fields):
    if not isinstance(layer, QgsVectorLayer):
        return False
    field_names = {f.name(): f.type() for f in layer.fields()}
    for name, ftype in required_fields.items():
        if name not in field_names or field_names[name] != ftype:
            return False
    return True



class MaptextAnnotatorDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    required_fields = {
        "Word Transcription": QVariant.String,
        "Phrase Transcription": QVariant.String,
        "Reference Image": QVariant.String,
        "Lat": QVariant.Double,
        "Lon": QVariant.Double,
        "Bounding Points": QVariant.String,
        "Bounding Box": QVariant.String,
        "Oriented Bounding Box": QVariant.String,
        "Upper Bezier": QVariant.String,
        "Lower Bezier": QVariant.String,
        "Mean Altitude": QVariant.Double,
        "Median Altitude": QVariant.Double,
        "Max Altitude": QVariant.Double,
        "Min Altitude": QVariant.Double,
        "Mean Slope": QVariant.Double,
        "Median Slope": QVariant.Double,
        "Max Slope": QVariant.Double,
        "Min Slope": QVariant.Double,
        "Complexity": QVariant.Double,
        "Contrast": QVariant.Double,
        "Word uuid": QVariant.String,
        "Link to previous Word": QVariant.Bool,
        "Create Date": QVariant.DateTime
    }

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(MaptextAnnotatorDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.demLayerCombo.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.annotationLayerCombo.setFilters(QgsMapLayerProxyModel.PolygonLayer)

        # Run once on init
        self.filter_unfit_rows()

        # Recheck whenever layers are added or removed
        QgsProject.instance().layersAdded.connect(self.filter_unfit_rows)
        QgsProject.instance().layersRemoved.connect(self.filter_unfit_rows)

    def filter_unfit_rows(self, *args):
        excluded = []
        for layer in QgsProject.instance().mapLayers().values():
            if not isinstance(layer, QgsVectorLayer):
                excluded.append(layer)
                continue
            if not layer_has_required_fields(layer, self.required_fields):
                excluded.append(layer)
        self.annotationLayerCombo.setExceptedLayerList(excluded)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
